-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dirty_secrets.users
(
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fname character varying(40) COLLATE pg_catalog."default" NOT NULL,
    lname character varying(40) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS dirty_secrets.secrets
(
    secret_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    title character varying(50) COLLATE pg_catalog."default",
    contents character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT secrets_pkey PRIMARY KEY (secret_id)
);

ALTER TABLE IF EXISTS dirty_secrets.secrets
    ADD CONSTRAINT secrets_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES dirty_secrets.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;

BEGIN;

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Jack', 'Bauer');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Angelo', 'Pixoli');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Rey', 'Nacho');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Salvador', 'Daly');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Linda', 'Boutique');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Lobster','King');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Cristina','La Bella');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Vlad', 'The Bad');

INSERT INTO dirty_secrets.users (fname, lname)
VALUES ('Rocket', 'Racoon');


COMMIT;
END;


-----------------------------------------
BEGIN;

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (1, 'Secret 1 title','secret 1 content.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (1, 'Secret 2 title','secret 2 cotent.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (2, 'secret 3 title','secret 3 content.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (2, 'secret 4 title','secret 4 content.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (3, 'secret 5 title','secret 5 content.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (3, 'secret 6 title','secret 6 content.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (4, 'secret 7 title','secret 7 content.');

INSERT INTO dirty_secrets.secrets (user_id, title, contents)
VALUES (4, 'secret 8 title','secret 8 content.');

COMMIT;
END;


